version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest 
    environment:
      - OCAML_VERSION: "4.06.0"
    steps:
      - checkout
      - run: apt-get update && apt-get install -y wget
      - run: wget -O ${HOME}/opam https://github.com/ocaml/opam/releases/download/2.0.0-rc/opam-2.0.0-rc-x86_64-linux
      - run: opam --version 
